### ISSUE TITLE
[feat] 엘라스틱서치 공연 아이디 추가

### ISSUE THREAD

**Issue by kdmin0706** [HalfGallonTeam/WithCon_BE#106]
### 📄 Describe
엘라스틱 서치 조회 시에 공연 정보 추가

### ✅ Tasks
- [x] 엘라스틱서치 도큐먼트 공연 정보 추가
- [x] 엘라스틱서치 공연 정보 추가 API  진행
- [x] 검색어 자동완성 시에 공연 아이디에 따른 태그 정보 조회

### 🙋🏻 More
_No_Response_
