### ISSUE TITLE
[feat] 채팅방 입장, 구독, 퇴장 여부 확인

### ISSUE THREAD

**Issue by kdmin0706** [HalfGallonTeam/WithCon_BE#127]
### 📄 Describe
- 채팅방 입장(연결) 시에 `Authorization` 토큰을 활용하여 해당 유저 정보를 `stomp` 에 저장한다.
- 채팅방 구독 시에 `sessionId`를 활용하여 유저 정보 및 채팅방 정보를 저장한다.
- 채팅방 퇴장 시에 `구독`시에 저장했던 데이터를 불러와서 해당 데이터를 검증한 후에 삭제한다.

### ✅ Tasks
- [x] Stomp 연결 시에 `Authorization` 토큰을 활용하여 유저 정보 저장
- [x] Stomp 구독 시에 `sessionId`와 연결 시에 저장했던 유저 정보를 활용하여 데이터를 `redis`에 저장
- [x] Stomp 삭제 시에 `redis`에서 데이터를 불러와서 해당 데이터 검증 후에 삭제한다.

### 🙋🏻 More
_No_Response_
