### ISSUE TITLE
[feat] Github webook, 배포 자동화

### ISSUE THREAD

**Issue by wndgndi** [HalfGallonTeam/WithCon_BE#37]
### 📄 Describe
새로운 기능에 대한 설명을 작성해 주세요.
- Github webhook을 통해 Jenkins에 이벤트가 발생
- jenkins의 파이프라인을 통한 배포 자동화 

### ✅ Tasks
해야 하는 일에 대한 Tasks를 작성해 주세요.

- [x] Dockerfie 작성
- [x] docker-compose.yml 작성
- [x] .env 작성
- [x] Github webhook 테스트
- [x] 배포 자동화 테스트

### 🙋🏻 More
더 하고 싶은 말이 있다면 작성해 주세요.
